; PASS2 CORE++ INFERENCES

; ---- Speaker Inference ----
(speaker line:15 he :confidence 0.95)
(speaker line:21 Geralt :confidence 0.95)
(speaker line:28 he :confidence 0.95)
(speaker line:105 Geralt :confidence 0.95)
(speaker line:109 Oreck :confidence 0.95)
(speaker line:111 Geralt :confidence 0.95)
(speaker line:121 Oreck :confidence 0.95)
(speaker line:134 Oreck :confidence 0.95)
(speaker line:188 Oreck :confidence 0.95)
(speaker line:200 Geralt :confidence 0.95)
(speaker line:228 Geralt :confidence 0.95)
(speaker line:245 he :confidence 0.95)
(speaker line:271 Oreck :confidence 0.95)
(speaker line:297 Geralt :confidence 0.95)
(speaker line:376 he :confidence 0.95)
(speaker line:432 she :confidence 0.95)
(speaker line:506 Geralt :confidence 0.95)
(speaker line:524 she :confidence 0.95)
(speaker line:534 he :confidence 0.95)
(speaker line:627 she :confidence 0.95)
(speaker line:646 Geralt :confidence 0.95)
(speaker line:821 Geralt :confidence 0.95)
(speaker line:872 Geralt :confidence 0.95)
(speaker line:904 Geralt :confidence 0.95)
(speaker line:954 Oreck :confidence 0.95)
(speaker line:989 Oreck :confidence 0.95)
(speaker line:1007 he :confidence 0.95)
(speaker line:1028 he :confidence 0.95)
(speaker line:1109 he :confidence 0.95)
(speaker line:1146 Geralt :confidence 0.95)

; ---- Pronoun → Actor ----

; ---- Emotions ----

; ---- Actions ----
(action line:86 retreat :confidence 0.90)
(action line:152 creation :confidence 0.90)
(action line:204 attack :confidence 0.90)
(action line:235 creation :confidence 0.90)
(action line:396 retreat :confidence 0.90)
(action line:397 creation :confidence 0.90)
(action line:425 attack :confidence 0.90)
(action line:501 retreat :confidence 0.90)
(action line:595 attack :confidence 0.90)
(action line:950 creation :confidence 0.90)
(action line:1017 retreat :confidence 0.90)
(action line:1032 submission :confidence 0.90)
(action line:1052 retreat :confidence 0.90)
(action line:1075 attack :confidence 0.90)

; ---- Thoughts ----

