; PASS2 CORE++ INFERENCES

; ---- Speaker Inference ----
(speaker line:54 she :confidence 0.95)
(speaker line:78 Geralt :confidence 0.95)
(speaker line:132 Geralt :confidence 0.95)
(speaker line:215 he :confidence 0.95)
(speaker line:216 she :confidence 0.95)
(speaker line:299 Geralt :confidence 0.95)
(speaker line:353 Oreck :confidence 0.95)
(speaker line:386 Geralt :confidence 0.95)
(speaker line:422 Oreck :confidence 0.95)
(speaker line:444 Geralt :confidence 0.95)
(speaker line:504 Geralt :confidence 0.95)
(speaker line:631 he :confidence 0.95)
(speaker line:657 Geralt :confidence 0.95)
(speaker line:708 Geralt :confidence 0.95)
(speaker line:951 Luminaire :confidence 0.95)
(speaker line:1001 Luminaire :confidence 0.95)
(speaker line:1010 Luminaire :confidence 0.95)
(speaker line:1016 Geralt :confidence 0.95)
(speaker line:1029 Geralt :confidence 0.95)
(speaker line:1044 Geralt :confidence 0.95)
(speaker line:1066 Geralt :confidence 0.95)
(speaker line:1072 Geralt :confidence 0.95)

; ---- Pronoun → Actor ----

; ---- Emotions ----

; ---- Actions ----
(action line:237 submission :confidence 0.90)
(action line:257 submission :confidence 0.90)
(action line:655 creation :confidence 0.90)
(action line:773 attack :confidence 0.90)
(action line:963 creation :confidence 0.90)
(action line:1023 creation :confidence 0.90)

; ---- Thoughts ----

