; PASS2 CORE++ INFERENCES

; ---- Speaker Inference ----

; ---- Pronoun → Actor ----

; ---- Emotions ----

; ---- Actions ----
(action line:10 creation :confidence 0.90)
(action line:403 creation :confidence 0.90)
(action line:432 creation :confidence 0.90)
(action line:453 creation :confidence 0.90)
(action line:459 creation :confidence 0.90)
(action line:466 creation :confidence 0.90)
(action line:648 submission :confidence 0.90)
(action line:669 submission :confidence 0.90)
(action line:689 creation :confidence 0.90)
(action line:804 creation :confidence 0.90)
(action line:860 creation :confidence 0.90)
(action line:929 creation :confidence 0.90)
(action line:942 retreat :confidence 0.90)
(action line:944 creation :confidence 0.90)
(action line:1021 creation :confidence 0.90)
(action line:1115 submission :confidence 0.90)
(action line:1303 submission :confidence 0.90)
(action line:1360 creation :confidence 0.90)
(action line:1884 attack :confidence 0.90)
(action line:1890 retreat :confidence 0.90)
(action line:1920 attack :confidence 0.90)
(action line:1932 retreat :confidence 0.90)
(action line:1975 attack :confidence 0.90)
(action line:1980 attack :confidence 0.90)
(action line:1981 attack :confidence 0.90)
(action line:1984 attack :confidence 0.90)
(action line:1989 creation :confidence 0.90)
(action line:1993 attack :confidence 0.90)
(action line:1993 creation :confidence 0.90)
(action line:2012 retreat :confidence 0.90)
(action line:2019 retreat :confidence 0.90)
(action line:2019 creation :confidence 0.90)
(action line:2023 retreat :confidence 0.90)
(action line:2055 creation :confidence 0.90)
(action line:2072 attack :confidence 0.90)
(action line:2081 creation :confidence 0.90)
(action line:2144 attack :confidence 0.90)
(action line:2146 attack :confidence 0.90)
(action line:2250 attack :confidence 0.90)
(action line:2250 creation :confidence 0.90)
(action line:2254 attack :confidence 0.90)
(action line:2486 creation :confidence 0.90)
(action line:2563 creation :confidence 0.90)

; ---- Thoughts ----

