; PASS2 CORE++ INFERENCES

; ---- Speaker Inference ----
(speaker line:19 he :confidence 0.95)
(speaker line:117 he :confidence 0.95)
(speaker line:142 he :confidence 0.95)
(speaker line:197 she :confidence 0.95)
(speaker line:206 Keen :confidence 0.95)
(speaker line:208 Isla :confidence 0.95)
(speaker line:219 Keen :confidence 0.95)
(speaker line:257 she :confidence 0.95)
(speaker line:289 Keen :confidence 0.95)
(speaker line:411 Thang :confidence 0.95)
(speaker line:499 he :confidence 0.95)

; ---- Pronoun → Actor ----

; ---- Emotions ----

; ---- Actions ----
(action line:6 attack :confidence 0.90)
(action line:87 attack :confidence 0.90)
(action line:101 creation :confidence 0.90)
(action line:107 attack :confidence 0.90)
(action line:111 submission :confidence 0.90)
(action line:153 creation :confidence 0.90)
(action line:254 attack :confidence 0.90)
(action line:313 attack :confidence 0.90)
(action line:390 creation :confidence 0.90)
(action line:430 submission :confidence 0.90)
(action line:430 attack :confidence 0.90)
(action line:449 attack :confidence 0.90)
(action line:513 creation :confidence 0.90)

; ---- Thoughts ----

