"""ENGIONALITY_SHOWROOM_PROOF_SUITE external probes.

These tools rehearse showroom handoff shapes only. They do not assert render,
canon, runtime, Trixel, Godot, MrLore, GodotSim, or Mechanimation authority.
"""

SUITE_NAME = "ENGIONALITY_SHOWROOM_PROOF_SUITE"

SHOWROOM_TOOLS_ARE_EXTERNAL_PROBES = True
SHOWROOM_ENGINES_ARE_ACTIVE_CODE = True
SHOWROOM_PROBES_ARE_NOT_SHOWROOM_IDENTITY = True
SHOWROOM_COORDINATES_PERFORMANCE = True
SHOWROOM_DOES_NOT_RENDER_FINAL_VIEW = True
SHOWROOM_DOES_NOT_PROVE_MOTION = True
SHOWROOM_DOES_NOT_AUTHORIZE_RUNTIME = True
